### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Plebicek** [Stredni-skola-managementu-a-grafiky/UP3AI_23#19]
Vymyslete navržení loga barevnost, velikosti. font-size, různé podklady. Jde o to, aby logo bylo nejvíce responzivní.

**Comment by dejwooos** [comment]
![image](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135697449/546f0d1c-1499-4eb3-ae50-5ec70e59ebec)

**Comment by dejwooos** [comment]
![image](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135697449/482e1e1d-5370-4645-a100-a3a0f41bf181)

**Comment by dejwooos** [comment]
![image](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135697449/116e7cec-b881-479f-add8-ca013f5aa8b6)

**Comment by dejwooos** [comment]
![logo kdestosehnal](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135697449/e8f91a09-3b2d-4c6f-888a-1938cd638d43)

**Comment by dejwooos** [comment]
![logo kdestosehnal](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135697449/b924d6e4-280d-40e9-9adb-d2842e746356)

**Comment by Luckynox** [comment]
![Výherceeee](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135697501/73b38e5d-7792-4ffc-a2ce-bfff6cb494aa)
![User](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135697501/88ced5db-3295-4d34-a7dc-6792d3d4b65f)
![Lupa](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135697501/866579bc-057e-4564-a3d9-fb4ecc4e6f97)

**Comment by Luckynox** [comment]
![Výherceeee](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135697501/19f9256f-1b4d-4060-bea2-8f084daa6e5d)
![User](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135697501/6fbd0ba7-5fb0-41ae-96d6-37ea7d0d56f2)
![Lupa](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135697501/a1133ef7-0091-429c-aa7f-614e974e2714)

**Comment by Luckynox** [comment]
![Uploading Lupa.png…]()

**Comment by Luckynox** [comment]
![Lupa](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135697501/063077e3-f641-41d2-99cb-f6e9b19e9bd7)

**Comment by Luckynox** [comment]
![User](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135697501/00c21e02-78e0-450c-b713-b1e84c7a9a99)
![Lupa](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135697501/5ca0a772-cc0e-47b7-8dcd-032f5ea4c0ba)

**Comment by Luckynox** [comment]
![llupa](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135697501/86cac790-ec0a-498a-8938-5364e461c399)

**Comment by Luckynox** [comment]
![Výherceeeeeeeee](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135697501/348e3e36-70d5-436e-bb77-8e14ea32cd52)

**Comment by Luckynox** [comment]
![Lupaaa](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135697501/a81fb752-5e82-4d3d-a639-9405d7213814)
