### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by Plebicek** [Stredni-skola-managementu-a-grafiky/UP3AI_23#20]
Připravení favicon velikosti

**Comment by jirihruby962** [comment]
![favicon](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135667894/85b9d6f5-d995-48f4-89ad-c8a95fa2af0b)

**Comment by jirihruby962** [comment]
![image](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135667894/7c1c7745-a3ac-4e49-b61a-56961746081f)
