### ISSUE TITLE
Use-case diagram

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI_23#4]
Na základě #3 vytvořte use-case diagram.

**Comment by MarekMestka** [comment]
![usecaseD drawio](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135661191/3f3be483-7de6-4210-8f5f-b3af8b491124)
[usecaseD.zip](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/files/11673982/usecaseD.zip)


Jirka to schválil, když tak něco dodělám. 
Seřvat když tak Hrubku.

**Comment by MarekMestka** [comment]
![usecaseD drawio](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135661191/96955296-d072-4688-8c0e-c3aaa3e164ff)
[usecaseD zip.zip](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/files/11675196/usecaseD.zip.zip)
Upravený diagram, nelze odevzdat ve formátu drawio, je to tedy zazipované.
