### ISSUE TITLE
Register page

### ISSUE THREAD

**Issue by Plebicek** [Stredni-skola-managementu-a-grafiky/UP3AI_23#47]
Vytvořit html a css pro register

**Comment by MarekMestka** [comment]
čus, bohužel mi nejde git doma (netušim proč), ale začal jsem dělat tuhle page, takže hrubý základ tam je, jen si tam hoďte ikony a nějakej ten obrázek. 
a soubor přihoďte do složky php
[register.zip](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/files/11682022/register.zip)

**Comment by Lacikosz** [comment]
Čau, tohle se dávalo Nichito, když  se podíváš je k tomu přídán, takže tak. K tomu Nichita to má už hotové.

**Comment by ImOnTheBeachToo** [comment]
![Screenshot (4)](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI_23/assets/135811495/d4c013c1-e393-4b76-ae2e-f1dd04e52d96)
ja tu mam i javascript, a design vypada jinak ted Viktor ho zmenil

**Comment by MarekMestka** [comment]
jo oka guys, to jsem nevedel, ze je to hotovy:D Ale kdyby neco tak muzete pouzit neco z toho kodu. Jdou mi trhat osmicku tak gl vsem
