### ISSUE TITLE
Základní grafické rozvržení webu

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI_23#5]
Načrtnout obecné rozložení webu do grafického návrhu, které bude následně implementováno pomocí HTML5 strukturálních tagů. Jedná se o obecný návrh pro obrazovku PC / notebooku, který bude použitý na všech stránkách webu.

Strukturální tagy HTML5: https://www.jakpsatweb.cz/html/html5-strukturni.html

Odevzdání:
    struktura.png
    zdrojové soubory

**Comment by MarekMestka** [comment]
https://www.figma.com/file/SeKcpJmGmZXkvj0ipG8nzD/kdestosehnal?type=design&node-id=0-1&t=9ihsONfbO6ASlpTo-0
