### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by JindrichViktor** [Stredni-skola-managementu-a-grafiky/UP3AI_23#58]
Udělat responsivní verzi upraveného Wireframu pro mobily. Rozeberte si práci mezi sebe já si beru stránku item.

**Comment by Luckynox** [comment]
uděláno favourite a main

**Comment by JindrichViktor** [comment]
Item taky done

**Comment by JindrichViktor** [comment]
Responsivní design stránek je done
